name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}   
    - name: Install dependencies
      run: |
        cd RequestModelConverters
        dotnet restore
    - name: Build
      run: |
        cd RequestModelConverters
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd RequestModelConverters
        dotnet test
    - name: Pack
      run: |
        cd RequestModelConverters
        dotnet pack -c Release -o out
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: RequestModelConverters/RequestModelConverters/bin/Release/*.nupkg
  deploy:
    name: Deploy nuget Package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download result from Build
        uses: actions/download-artifact@v2
        with:
          name: Package
          path: package.nupkg
      - name: Push to github-repo
        run: dotnet nuget push package.nupkg